### PR TITLE
Synthetic module support

### PR DESCRIPTION
**Pull request by wumb0**
Found the need for synthetic module support, so I implemented it along with a few other helper methods.
I bumped the windows-rs version, so it might break snapshot if merged. You could just cherry pick the two other commits, if you'd like. 

I'm going to keep using this fork for some of my work unless merged, but would rather contribute it back! Open to feedback, of course.

### CODE REVIEW

**Comment by 0vercl0k** [comment]
Woot this looks awesome @wumb0 🥳🥳

I am currently traveling but will look at that once I'm back home (should be able to do that beginning of November; will also follow-up on your `wtf`'s issues 😅) if that's okay with you.

And yes I am absolutely interested in reviewing/merging those changes :)

Cheers

**Comment by wumb0** [comment]
Updated commits to fix formatting issues (thought I ran it, but forgot +nightly so I'm not sure it actually ran).

**Comment by 0vercl0k** [comment]
How does this look @wumb0? I didn't do much tbh, just a few nits here and there.

I'll wait for your 👍🏼 and get this merged!

Thank you again.

Cheers

**Comment by wumb0** [comment]
looks good to me!

**Comment by 0vercl0k** [comment]
Okay I also pushed [v0.3](https://crates.io/crates/dbgeng); lemme know if anything is wrong (`docs.rs` seems to fail to build the docs with this version... I'll have to check out what's up 😅).

Cheers

**Comment by 0vercl0k** [comment]
Okay, I pushed v0.3.1 to address this, we should be good now!

**Pull request merged**
